In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('data\\nst.csv')

C:\Users\Luther\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
df.head()

  contentId               clientId  timeOnPage      date device_deviceCategory
0    417517  2141495723.1510454477        1487  20181004                mobile
1    417536  2141495723.1510454477          77  20181004                mobile
2    417605  2141500465.1517105204          46  20181004                mobile
3    417605  2141500465.1517105204          46  20181004                mobile
4    417693  2043529148.1477272418           1  20181004                mobile

In [12]:
aa = df['contentId'].value_counts()

In [32]:
aa.describe()

count    27609.000000
mean        49.118367
std        577.508923
min          1.000000
25%          1.000000
50%          2.000000
75%          5.000000
max      33666.000000
Name: contentId, dtype: float64

In [34]:
## extract list of artilces above 
article_list_aboveMean = aa [ aa.values > 50 ]

In [35]:
article_list_aboveMean

417605    33666
417996    27417
417787    25389
416988    23277
416614    22423
418137    19331
417636    18395
418179    17321
416616    16232
417751    16159
416773    15674
416915    14941
416614    14868
418451    12829
416687    12741
417933    12517
417693    11744
417706    10814
417605    10245
416592    10096
416616     9877
416773     9572
417373     9492
417428     9116
417614     8695
417787     8502
418295     8427
418084     8143
416687     7969
418054     7766
          ...
416433       52
300375       52
380344       52
415270       52
349222       52
395464       52
416579       52
395462       52
417293       52
417157       52
404029       52
362900       52
414620       52
360404       52
408693       52
287884       52
417157       52
399247       51
417577       51
416003       51
324683       51
349222       51
415151       51
416835       51
416192       51
408582       51
418291       51
414788       51
400092       51
415649       51
Name: contentId, Length: 1721, dtype: int64

In [37]:
article_list_aboveMean.index

Index(['417605', '417996', '417787', '416988', '416614', '418137', '417636',
       '418179', '416616', '417751',
       ...
       '324683',   349222, '415151', '416835',   416192, '408582',   418291,
       '414788', '400092', '415649'],
      dtype='object', length=1721)

In [46]:
df[ df['contentId']== 400092]

,contentId,clientId,timeOnPage,date,device_deviceCategory
420893,400092,1258416101.1444570892,445,20181004,tablet
428301,400092,1817326455.1528807074,1252,20181003,mobile
439830,400092,1840959339.1528095128,192,20181003,mobile
441810,400092,1853360387.1535526096,133,20181003,mobile
445975,400092,1731542588.1451403046,649,20181003,mobile
445976,400092,1731542588.1451403046,649,20181003,mobile
450694,400092,1795187686.1507506871,75,20181003,mobile
457707,400092,2055147211.1482590241,73,20181003,mobile
458336,400092,1906003846.1508077387,59,20181003,mobile
460868,400092,1918271217.1512198499,137,20181003,mobile
466354,400092,1929239126.1538461244,330,20181003,desktop
472474,400092,2095284354.1517482219,216,20181003,mobile
472475,400092,2095284354.1517482219,216,20181003,mobile
474162,400092,2032173979.1517456720,43,20181003,mobile
481179,400092,amp-V7ShBihwoc6yfIDVXdOkBw,148,20181003,mobile
489921,400092,603509998.1535855463,34,20181003,mobile
497267,400092,547652162.1517399494,285,20181003,mobile
497269,400092,547652162.1517399494,285,20181003,mobile
500049,400092,556050472.1488966029,103,20181003,mobile
505362,400092,498501692.1515907300,72,20181003,mobile
509767,400092,430687130.1505615513,209,20181003,tablet
515886,400092,591654788.1507643581,115,20181003,mobile
521591,400092,757094374.1512355283,114,20181003,desktop
655768,400092,1649344402.1524111493,250,20181001,desktop
669827,400092,amp-OVusBcrIuCnTFD9vMDNK7A,247,20181001,mobile
669829,400092,amp-OVusBcrIuCnTFD9vMDNK7A,247,20181001,mobile
681424,400092,612301082.1504317432,285,20181001,mobile
685226,400092,499956216.1522786021,72,20181001,mobile
699759,400092,521393798.1538374895,465,20181001,desktop
745969,400092,84254929.1493790917,246,20181001,desktop
1093442,400092,119470964.1520983208,222,20181003,mobile
1093444,400092,119470964.1520983208,222,20181003,mobile
1093723,400092,187010248.1536879638,84,20181003,mobile
1104635,400092,290918551.1467025294,35,20181003,mobile
1137376,400092,865499630.1538488425,6360,20181002,mobile
1157712,400092,1115868162.1493171921,1969,20181002,desktop
1323529,400092,amp-5gCvMqI7xmeSYTolmrxkfw,629,20181004,mobile
1323530,400092,amp-5gCvMqI7xmeSYTolmrxkfw,629,20181004,mobile
1332073,400092,1641576258.1537352135,256,20181004,mobile

In [36]:
df[ df['contentId']== 415649]

,contentId,clientId,timeOnPage,date,device_deviceCategory
442975,415649,1776577986.1538229374,6,20181003,mobile
444866,415649,1571707928.1538568276,330,20181003,tablet
444867,415649,1571707928.1538568276,330,20181003,tablet
444868,415649,1571707928.1538568276,330,20181003,tablet
459637,415649,1910069281.1538548336,127,20181003,mobile
459638,415649,1910069281.1538548336,127,20181003,mobile
459639,415649,1910069281.1538548336,127,20181003,mobile
470993,415649,1945117248.1538564827,79,20181003,mobile
477048,415649,1965483452.1530893773,864,20181003,mobile
477049,415649,1965483452.1530893773,864,20181003,mobile
514553,415649,518411433.1538577119,4,20181003,mobile
663397,415649,749285838.1538368245,1013,20181001,desktop
667316,415649,819021246.1395129860,3835,20181001,desktop
669497,415649,825962323.1534125424,1,20181001,desktop
670310,415649,713606874.1534225487,1,20181001,mobile
714577,415649,659639121.1510618652,1,20181001,desktop
736488,415649,123104540.1535333352,3349,20181001,desktop
767719,415649,1278253245.1518743539,2,20181005,desktop
1113381,415649,1718547281.1511092905,1,20181002,mobile
1113660,415649,263429686.1538413145,2,20181002,mobile
1114910,415649,1776577986.1538229374,6,20181002,mobile
1114994,415649,1718547281.1511092905,1,20181002,mobile
1115371,415649,718476508.1538427677,2,20181002,tablet
1116155,415649,1763483108.1533350876,1,20181002,desktop
1116291,415649,379763998.1520225964,1,20181002,mobile
1117526,415649,1567243957.1538458058,1,20181002,mobile
1117997,415649,9163799.1538457247,1,20181002,mobile
1119341,415649,642739158.1538435475,1,20181002,desktop
1119751,415649,796738941.1538445751,1,20181002,desktop
1151259,415649,1765956680.1526025323,1,20181002,mobile
1154982,415649,1014110131.1516605965,126,20181002,desktop
1323712,415649,1776577986.1538229374,3,20181004,mobile